version: '3.8'

services:
  frontend:
    container_name: pet-clinic-frontend
    build: ./frontend
    restart: always
    env_file: ./.env
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - pcbridge
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

  backend:
    container_name: pet-clinic-backend
    build: ./backend
    env_file: ./.env
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - pcbridge
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

networks:
  pcbridge:
    driver: bridge
